name: Stable version build
on:
  push:
    branches: [master,webinar]

jobs:
  push_to_registry:
    name: Push to docker actions
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENGH }}
          registry: ghcr.io
          repository: ghcr.io/TRAD3R/rebrain-k8s/webinar
          tag_with_ref: true
#        with:
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rebrain_k8s:latest