name: Stable version build
on:
  push:
    branches: [master,webinar]

jobs:
  push_to_registry:
    name: Push to docker actions
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4

      # Шаг 2: Логин в GHCR с использованием секрета GHCR_PAT
      - name: Log in to GHCR
        run: echo "${{ secrets.TOKENGH }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Шаг 3: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/rebrain_k8s/webinar:latest .

      # Шаг 4: Пуш Docker-образа в GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/rebrain_k8s/webinar:latest