name: Stable version build
on:
  push:
    branches: [master,webinar]

jobs:
  push_to_registry:
    name: Push to docker actions
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: push to repo
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ghcr.io
          repository: ghcr.io/trad3r/rebrain_k8s/webinar
          tag_with_ref: true